### ISSUE TITLE
Cannot npm install

### ISSUE THREAD

**Issue by EdoardoSchnell** [kingjan1999/platform-folders#13]
Hello, I'm trying to npm install but I receive the following error

```
$ npm i platform-folders@0.2.3

> platform-folders@0.2.3 install C:\Users\federico.ceriani\Documents\Projects\tester-setup\probe-srv\node_modules\platform-folders
> node-gyp rebuild


C:\Users\federico.ceriani\Documents\Projects\tester-setup\probe-srv\node_modules\platform-folders>if not defined npm_config_node_gyp (node "C:\Program 
Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: C:\Users\federico.ceriani\AppData\Local\Programs\Python\Python38-32\python.EXE -c import sys; print "%s.%s.%s" % 
sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\federico.ceriani\Documents\Projects\tester-setup\probe-srv\node_modules\platform-folders
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ws@7.2.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @crm40/probe@2.1.1-test.2 No description
npm WARN @crm40/probe@2.1.1-test.2 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! platform-folders@0.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the platform-folders@0.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\federico.ceriani\AppData\Roaming\npm-cache\_logs\2020-03-18T09_28_39_703Z-debug.log
```

I erroneously asked the same question to the maintainer of the c++ library and he suggested it could be the python version (3.8 instead of 2.7) although I cannot guarantee my package will be shipped on a machine with python 2.7... if this is in fact the problem, is there any way to circumvent this? Or am I missing something else?

Thank you

**Comment by kingjan1999** [comment]
Try updating `node-gyp` / npm. You're using version 3.8.0 while 6.1.0 is currently up to date (and brings support for Python 3) .

**Comment by EdoardoSchnell** [comment]
Ah, that's unfortunate, I'm tied down to that npm version... I'll find some other way round. Thank you anyway.
